USE [BUBUBIBI]
GO
/****** Object:  Table [dbo].[DEPARTMENT]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTMENT](
	[ID_DEPARTMENT] [int] IDENTITY(1,1) NOT NULL,
	[CITY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DEPARTMENT] PRIMARY KEY CLUSTERED 
(
	[ID_DEPARTMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DICT_ELEMENT]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DICT_ELEMENT](
	[ID_ELEMENT] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[PRINT_TIMESTAMP] [timestamp] NULL,
	[PRINT_TIME] [int] NULL,
 CONSTRAINT [PK_DICT_ELEMENT] PRIMARY KEY CLUSTERED 
(
	[ID_ELEMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DICT_PRINTER_STATUS]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DICT_PRINTER_STATUS](
	[ID_DICT_PRINTER_STATUS] [int] NOT NULL,
	[DESCRITPION] [nvarchar](100) NULL,
 CONSTRAINT [PK_DICT_PRINTER_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID_DICT_PRINTER_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DICT_RANGE_EMPLOYEE]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DICT_RANGE_EMPLOYEE](
	[ID_RANGE_EMPLOYEE] [int] IDENTITY(1,1) NOT NULL,
	[RANGE_NAME] [nchar](30) NOT NULL,
	[DESCRIPTION] [nchar](200) NULL,
	[ID_RANGE_EMPLOYEE_PARENT] [int] NULL,
 CONSTRAINT [PK_DICT_RANGE_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[ID_RANGE_EMPLOYEE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ELEMENT_SET]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ELEMENT_SET](
	[ID_ELEMENT_SET] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ELEMENT_SET] PRIMARY KEY CLUSTERED 
(
	[ID_ELEMENT_SET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ELEMENT_SET_SPECIFICATION]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ELEMENT_SET_SPECIFICATION](
	[ID_ELEMENT] [int] NOT NULL,
	[ID_ELEMENT_SET] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
 CONSTRAINT [PK_ELEMENT_SET_SPECIFICATION] PRIMARY KEY CLUSTERED 
(
	[ID_ELEMENT] ASC,
	[ID_ELEMENT_SET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[ID_EMPLOYEE] [int] IDENTITY(1,1) NOT NULL,
	[ID_RANGE_EMPLOYEE] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[SURNAME] [nvarchar](50) NOT NULL,
	[ID_DEPARTMENT] [int] NULL,
	[ID_EMPLOYEE_PARENT] [int] NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[ID_EMPLOYEE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE_TO_PRINTER]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE_TO_PRINTER](
	[ID_WORKER] [int] NOT NULL,
	[ID_PRINTER] [int] NOT NULL,
 CONSTRAINT [PK_EMPLOYEE_TO_PRINTER] PRIMARY KEY CLUSTERED 
(
	[ID_WORKER] ASC,
	[ID_PRINTER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MALFUNCTION]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MALFUNCTION](
	[ID_MALFUNCTION] [int] IDENTITY(1,1) NOT NULL,
	[ID_PRINTER] [int] NOT NULL,
	[START_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_MALFUNCTION] PRIMARY KEY CLUSTERED 
(
	[ID_MALFUNCTION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDER]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER](
	[ID_ORDER] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_DATE] [datetime] NOT NULL,
	[ORDER_START_DATE] [datetime] NULL,
	[ID_DEPARTMENT] [int] NULL,
	[TIME_TO_COMPLETE_ORDER_MINS] [int] NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED 
(
	[ID_ORDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDER_ELEMENT]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER_ELEMENT](
	[ID_ORDER_ELEMENT] [int] IDENTITY(1,1) NOT NULL,
	[ID_ORDER] [int] NOT NULL,
	[ID_ELEMENT] [int] NULL,
	[QUANTITY] [int] NOT NULL,
	[ID_ELEMENT_SET] [int] NULL,
 CONSTRAINT [PK_ORDER_ELEMENT] PRIMARY KEY CLUSTERED 
(
	[ID_ORDER_ELEMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRINTER]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRINTER](
	[PRINTER_UQ] [varchar](26) NOT NULL,
	[PRINTER_NAME] [nvarchar](50) NOT NULL,
	[ID_PRINTER_STATUS] [int] NOT NULL,
	[ID_PRINTER] [int] IDENTITY(1,1) NOT NULL,
	[ID_DEPARTMENT] [int] NULL,
 CONSTRAINT [PK_PRINTER_1] PRIMARY KEY CLUSTERED 
(
	[ID_PRINTER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRINTER_STATUS]    Script Date: 21.06.2023 17:06:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRINTER_STATUS](
	[ID_PRINTER_STATUS] [int] IDENTITY(1,1) NOT NULL,
	[END_DATE] [datetime] NULL,
	[ID_MALFUNCTION] [int] NOT NULL,
	[ID_DICT_PRINTER_STATUS] [int] NOT NULL,
 CONSTRAINT [PK_PRINTER_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID_PRINTER_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELEMENT_SET_SPECIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_ELEMENT_SET_SPECIFICATION_DICT_ELEMENT] FOREIGN KEY([ID_ELEMENT])
REFERENCES [dbo].[DICT_ELEMENT] ([ID_ELEMENT])
GO
ALTER TABLE [dbo].[ELEMENT_SET_SPECIFICATION] CHECK CONSTRAINT [FK_ELEMENT_SET_SPECIFICATION_DICT_ELEMENT]
GO
ALTER TABLE [dbo].[ELEMENT_SET_SPECIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_ELEMENT_SET_SPECIFICATION_ELEMENT_SET] FOREIGN KEY([ID_ELEMENT_SET])
REFERENCES [dbo].[ELEMENT_SET] ([ID_ELEMENT_SET])
GO
ALTER TABLE [dbo].[ELEMENT_SET_SPECIFICATION] CHECK CONSTRAINT [FK_ELEMENT_SET_SPECIFICATION_ELEMENT_SET]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_DEPARTMENT] FOREIGN KEY([ID_DEPARTMENT])
REFERENCES [dbo].[DEPARTMENT] ([ID_DEPARTMENT])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_DEPARTMENT]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_DICT_RANGE_EMPLOYEE] FOREIGN KEY([ID_RANGE_EMPLOYEE])
REFERENCES [dbo].[DICT_RANGE_EMPLOYEE] ([ID_RANGE_EMPLOYEE])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_DICT_RANGE_EMPLOYEE]
GO
ALTER TABLE [dbo].[EMPLOYEE_TO_PRINTER]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_TO_PRINTER_EMPLOYEE] FOREIGN KEY([ID_WORKER])
REFERENCES [dbo].[EMPLOYEE] ([ID_EMPLOYEE])
GO
ALTER TABLE [dbo].[EMPLOYEE_TO_PRINTER] CHECK CONSTRAINT [FK_EMPLOYEE_TO_PRINTER_EMPLOYEE]
GO
ALTER TABLE [dbo].[EMPLOYEE_TO_PRINTER]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_TO_PRINTER_PRINTER] FOREIGN KEY([ID_PRINTER])
REFERENCES [dbo].[PRINTER] ([ID_PRINTER])
GO
ALTER TABLE [dbo].[EMPLOYEE_TO_PRINTER] CHECK CONSTRAINT [FK_EMPLOYEE_TO_PRINTER_PRINTER]
GO
ALTER TABLE [dbo].[MALFUNCTION]  WITH CHECK ADD  CONSTRAINT [FK_MALFUNCTION_PRINTER] FOREIGN KEY([ID_PRINTER])
REFERENCES [dbo].[PRINTER] ([ID_PRINTER])
GO
ALTER TABLE [dbo].[MALFUNCTION] CHECK CONSTRAINT [FK_MALFUNCTION_PRINTER]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_DEPARTMENT] FOREIGN KEY([ID_DEPARTMENT])
REFERENCES [dbo].[DEPARTMENT] ([ID_DEPARTMENT])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_DEPARTMENT]
GO
ALTER TABLE [dbo].[ORDER_ELEMENT]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ELEMENT_DICT_ELEMENT] FOREIGN KEY([ID_ELEMENT])
REFERENCES [dbo].[DICT_ELEMENT] ([ID_ELEMENT])
GO
ALTER TABLE [dbo].[ORDER_ELEMENT] CHECK CONSTRAINT [FK_ORDER_ELEMENT_DICT_ELEMENT]
GO
ALTER TABLE [dbo].[ORDER_ELEMENT]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ELEMENT_ELEMENT_SET] FOREIGN KEY([ID_ELEMENT_SET])
REFERENCES [dbo].[ELEMENT_SET] ([ID_ELEMENT_SET])
GO
ALTER TABLE [dbo].[ORDER_ELEMENT] CHECK CONSTRAINT [FK_ORDER_ELEMENT_ELEMENT_SET]
GO
ALTER TABLE [dbo].[ORDER_ELEMENT]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ELEMENT_ORDER] FOREIGN KEY([ID_ORDER])
REFERENCES [dbo].[ORDER] ([ID_ORDER])
GO
ALTER TABLE [dbo].[ORDER_ELEMENT] CHECK CONSTRAINT [FK_ORDER_ELEMENT_ORDER]
GO
ALTER TABLE [dbo].[PRINTER]  WITH CHECK ADD  CONSTRAINT [FK_PRINTER_DEPARTMENT] FOREIGN KEY([ID_DEPARTMENT])
REFERENCES [dbo].[DEPARTMENT] ([ID_DEPARTMENT])
GO
ALTER TABLE [dbo].[PRINTER] CHECK CONSTRAINT [FK_PRINTER_DEPARTMENT]
GO
ALTER TABLE [dbo].[PRINTER_STATUS]  WITH CHECK ADD  CONSTRAINT [FK_PRINTER_STATUS_DICT_PRINTER_STATUS] FOREIGN KEY([ID_DICT_PRINTER_STATUS])
REFERENCES [dbo].[DICT_PRINTER_STATUS] ([ID_DICT_PRINTER_STATUS])
GO
ALTER TABLE [dbo].[PRINTER_STATUS] CHECK CONSTRAINT [FK_PRINTER_STATUS_DICT_PRINTER_STATUS]
GO
ALTER TABLE [dbo].[PRINTER_STATUS]  WITH CHECK ADD  CONSTRAINT [FK_PRINTER_STATUS_MALFUNCTION1] FOREIGN KEY([ID_MALFUNCTION])
REFERENCES [dbo].[MALFUNCTION] ([ID_MALFUNCTION])
GO
ALTER TABLE [dbo].[PRINTER_STATUS] CHECK CONSTRAINT [FK_PRINTER_STATUS_MALFUNCTION1]
GO
