USE BUBUBIBI

CREATE TRIGGER AVOIDING_OVER_36_HOURS_LENGTH  
ON ORDER_ELEMENT  
AFTER INSERT, UPDATE  
AS   
BEGIN    
	SELECT * INTO TEMPORARY_TABLE 
	FROM RETURN_TIME_NEEDED_TO_COMPLETE_ORDER()   

	IF EXISTS (SELECT * FROM TEMPORARY_TABLE T 
	WHERE T.Time_to_print_set > (36 * 60))   BEGIN     
	THROW 50001, 'Wartoœæ czasu potrzebnego do skompletowania tego zamówienia przekracza 36 godzin', 1;   
	END   
	DROP TABLE TEMPORARY_TABLE   
END